title: F.I.R.E.
description: Factor Investment Research Engine (The bundled opensource toolkit for book Navigating the Factor Zoo：The Science of Quantitative Investing.)
theme: just-the-docs

url: fire-institute.github.io

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template


color_scheme: dark